---
- name: EDA Hackathon Rulebook 
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: server down
      condition: event.alert.labels.job == "server" and event.alert.status == "firing"
      action:
        run_job_template:
          name: Demo Job Template
          job_args:
            extra_vars:
              src_username: Hackathon - Source Username
              src_password: Hackathon - Source Password
