---
- name: EDA Hackathon Rulebook
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      # ansible.eda.alertmanager:
      #   host: 0.0.0.0
      #   port: 5000
  rules:
    - name: server down
      # condition: event.alert.labels.job == "server" and event.alert.status == "firing"
      condition: event.payload.message == "Ansible is super cool"
      action:
        run_job_template:
          name: Demo Job Template
          job_args:
            extra_vars:
              src_username: Source Username
              src_password: Source Password
