- name: EDA Hackathon Playbook
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print the Source Username
      ansible.builtin.debug:
        msg: "EDA Custom Credential Username: {{ src_username }}"

    - name: Print the Source Password
      ansible.builtin.debug:
        msg: "EDA Custom Credential Password: {{ src_password }}"
