---
- name: Timeout test
  hosts: all
  gather_facts: false
  tasks:
    - name: Sleep for 4 hours
      wait_for:
        timeout: 14400
      delegate_to: localhost
      run_once: true

    - name: Sleep for 60 seconds
      wait_for:
        timeout: 60
      delegate_to: localhost
      run_once: true

    - name: Debug Hello World
      ansible.builtin.debug:
        msg: "Hello World"
