- name: EDA Hackathon Playbook
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print the vaulted message
      ansible.builtin.debug:
        msg: "Vault message: {{ vault_msg }}"

    - name: Print template name
      ansible.builtin.debug:
        msg: "Your job template variable: {{ job_template_name }}"
