---
name: 'Upgrade mgt-preprod based on releases tagged as prerelease'

on:
  release:
    types: [prereleased]

permissions:
  id-token: write
  contents: read

jobs:
  call-upgrade-base:
    uses: ./.github/workflows/test-workflow.yml
    with:
      dry_run: false
      auto_merge: true
      environment: preproduction
      deployment_type: management
      limit: mgt-preprod
      release_branch: ${{ github.ref_name }}
    secrets:
      inherit